<?php

/**
 * @file
 * Contains kaoqin.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function kaoqin_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kaoqin module.
    case 'help.page.kaoqin':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('考勤历史统计') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function kaoqin_theme() {
  return [
    'kaoqin' => [
      'render element' => 'children',
    ],
  ];
}
